network/api/urls.py
from rest_framework import routers
from network.api import views


router = routers.DefaultRouter()

router.register(r'jobs', views.JobView, base_name='jobs')
router.register(r'data', views.ObservationView, base_name='data')
router.register(r'observations', views.ObservationView, base_name='observations')
router.register(r'settings', views.SettingsView, base_name='settings')

api_urlpatterns = router.urls

network/base/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from network.base import views

base_urlpatterns = ([
    url(r'^$', views.index, name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='base/about.html'), name='about'),
    url(r'^robots\.txt$', views.robots, name='robots'),
    url(r'^settings_site/$', views.settings_site, name='settings_site'),

    # Observations
    url(r'^observations/$', views.ObservationListView.as_view(), name='observations_list'),
    url(r'^observations/(?P<id>[0-9]+)/$', views.observation_view,
        name='observation_view'),
    url(r'^observations/(?P<id>[0-9]+)/delete/$', views.observation_delete,
        name='observation_delete'),
    url(r'^observations/new/$', views.observation_new, name='observation_new'),
    url(r'^prediction_windows/(?P<sat_id>[\w.@+-]+)/(?P<transmitter>[\w.@+-]+)/'
        '(?P<start_date>.+)/(?P<end_date>.+)/(?P<station_id>[\w.@+-]+)/$',
        views.prediction_windows, name='prediction_windows_filtered'),
    url(r'^prediction_windows/(?P<sat_id>[\w.@+-]+)/(?P<transmitter>[\w.@+-]+)/'
        '(?P<start_date>.+)/(?P<end_date>.+)/$',
        views.prediction_windows, name='prediction_windows'),
    url(r'^observation_verify/(?P<id>[0-9]+)/$', views.observation_verify,
        name='observation_verify'),
    url(r'^observation_mark_bad/(?P<id>[0-9]+)/$', views.observation_mark_bad,
        name='observation_mark_bad'),

    # Stations
    url(r'^stations/$', views.stations_list, name='stations_list'),
    url(r'^stations/(?P<id>[0-9]+)/$', views.station_view, name='station_view'),
    url(r'^stations/(?P<id>[0-9]+)/delete/$', views.station_delete, name='station_delete'),
    url(r'^stations/edit/$', views.station_edit, name='station_edit'),
    url(r'^stations_all/$', views.StationAllView.as_view({'get': 'list'}), name='stations_all'),

    # Satellites
    url(r'^satellites/(?P<id>[0-9]+)/$', views.satellite_view, name='satellite_view'),
    url(r'^satellite_position/(?P<sat_id>[0-9]+)/$', views.satellite_position,
        name='satellite_position'),
], 'base')

network/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve

from avatar import urls as avatar_urls
from allauth import urls as allauth_urls

from network.base.urls import base_urlpatterns
from network.users.urls import users_urlpatterns
from network.api.urls import api_urlpatterns

handler404 = 'network.base.views.custom_404'
handler500 = 'network.base.views.custom_500'

urlpatterns = [
    # Base urls
    url(r'^', include(base_urlpatterns)),

    url(r'^admin/', admin.site.urls),
    url(r'^users/', include(users_urlpatterns)),
    url(r'^accounts/', include(allauth_urls)),
    url(r'^avatar/', include(avatar_urls)),

    url(r'^api/', include(api_urlpatterns))
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT}),
    ]

network/users/urls.py
from django.conf.urls import url

from network.users import views

users_urlpatterns = ([
    url(r'^redirect/$', views.UserRedirectView.as_view(), name='redirect_user'),
    url(r'^update/$', views.UserUpdateView.as_view(), name='update_user'),
    url(r'^(?P<username>[\w.@+-]+)/$', views.view_user, name='view_user'),
], 'users')

network/base/models.py
import os
from datetime import datetime, timedelta
from PIL import Image
from shortuuidfield import ShortUUIDField

from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.dispatch import receiver
from django.db import models
from django.urls import reverse
from django.utils.html import format_html
from django.utils.timezone import now

from network.users.models import User
from network.base.helpers import get_apikey


RIG_TYPES = ['Radio', 'SDR']
ANTENNA_BANDS = ['HF', 'VHF', 'UHF', 'L', 'S', 'C', 'X', 'KU']
ANTENNA_TYPES = (
    ('dipole', 'Dipole'),
    ('yagi', 'Yagi'),
    ('helical', 'Helical'),
    ('parabolic', 'Parabolic'),
    ('vertical', 'Verical'),
    ('turnstile', 'Turnstile'),
    ('quadrafilar', 'Quadrafilar'),
    ('eggbeater', 'Eggbeater'),
    ('lindenblad', 'Lindenblad'),
)
OBSERVATION_STATUSES = (
    ('unknown', 'Unknown'),
    ('verified', 'Verified'),
    ('data_not_verified', 'Has Data, Not Verified'),
    ('no_data', 'No Data'),
)
SATELLITE_STATUS = ['alive', 'dead', 're-entered']


class Rig(models.Model):
    """Model for Rig types."""
    name = models.CharField(choices=zip(RIG_TYPES, RIG_TYPES), max_length=10)
    rictld_number = models.PositiveIntegerField(blank=True, null=True)

    def __unicode__(self):
        return '{0}: {1}'.format(self.name, self.rictld_number)


class Mode(models.Model):
    name = models.CharField(max_length=10, unique=True)

    def __unicode__(self):
        return self.name


class Antenna(models.Model):
    """Model for antennas tracked with SatNOGS."""
    frequency = models.PositiveIntegerField()
    frequency_max = models.PositiveIntegerField()
    band = models.CharField(choices=zip(ANTENNA_BANDS, ANTENNA_BANDS),
                            max_length=5)
    antenna_type = models.CharField(choices=ANTENNA_TYPES, max_length=15)

    def __unicode__(self):
        return '{0} - {1} - {2} - {3}'.format(self.band, self.antenna_type,
                                              self.frequency,
                                              self.frequency_max)


class Station(models.Model):
    """Model for SatNOGS ground stations."""
    owner = models.ForeignKey(User, related_name="ground_stations",
                              on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=45)
    image = models.ImageField(upload_to='ground_stations', blank=True)
    alt = models.PositiveIntegerField(help_text='In meters above ground')
    lat = models.FloatField(validators=[MaxValueValidator(90),
                                        MinValueValidator(-90)])
    lng = models.FloatField(validators=[MaxValueValidator(180),
                                        MinValueValidator(-180)])
    qthlocator = models.CharField(max_length=255, blank=True)
    location = models.CharField(max_length=255, blank=True)
    antenna = models.ManyToManyField(Antenna, blank=True,
                                     help_text=('If you want to add a new Antenna contact '
                                                '<a href="https://community.satnogs.org/" '
                                                'target="_blank">SatNOGS Team</a>'))
    featured_date = models.DateField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    last_seen = models.DateTimeField(null=True, blank=True)
    horizon = models.PositiveIntegerField(help_text='In degrees above 0', default=10)
    uuid = models.CharField(db_index=True, max_length=100, blank=True)
    rig = models.ForeignKey(Rig, related_name='ground_stations',
                            on_delete=models.SET_NULL, null=True, blank=True)
    description = models.TextField(max_length=500, blank=True)

    class Meta:
        ordering = ['-active', '-last_seen']

    def get_image(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        else:
            return settings.STATION_DEFAULT_IMAGE

    @property
    def online(self):
        try:
            heartbeat = self.last_seen + timedelta(minutes=int(settings.STATION_HEARTBEAT_TIME))
            return self.active and heartbeat > now()
        except:
            return False

    def state(self):
        if self.online:
            return format_html('<span style="color:green">Online</span>')
        else:
            return format_html('<span style="color:red">Offline</span>')

    @property
    def success_rate(self):
        observations = self.observations.all().count()
        success = self.observations.exclude(payload='').count()
        if observations:
            return int(100 * (float(success) / float(observations)))
        else:
            return False

    @property
    def apikey(self):
        return get_apikey(user=self.owner)

    def __unicode__(self):
        return "%d - %s" % (self.pk, self.name)


class Satellite(models.Model):
    """Model for SatNOGS satellites."""
    norad_cat_id = models.PositiveIntegerField()
    name = models.CharField(max_length=45)
    names = models.TextField(blank=True)
    image = models.CharField(max_length=100, blank=True, null=True)
    manual_tle = models.BooleanField(default=False)
    status = models.CharField(choices=zip(SATELLITE_STATUS, SATELLITE_STATUS),
                              max_length=10, default='alive')

    class Meta:
        ordering = ['norad_cat_id']

    def get_image(self):
        if self.image:
            return self.image
        else:
            return settings.SATELLITE_DEFAULT_IMAGE

    @property
    def latest_tle(self):
        try:
            latest_tle = Tle.objects.filter(satellite=self).latest('updated')
            return latest_tle
        except Tle.DoesNotExist:
            return False

    @property
    def tle_no(self):
        try:
            line = self.latest_tle.tle1
            return line[65:68]
        except:
            return False

    @property
    def tle_epoch(self):
        try:
            line = self.latest_tle.tle1
            yd, s = line[18:32].split('.')
            epoch = (datetime.strptime(yd, "%y%j") +
                     timedelta(seconds=float("." + s) * 24 * 60 * 60))
            return epoch
        except:
            return False

    @property
    def data_count(self):
        return Observation.objects.filter(satellite=self).count()

    @property
    def verified_count(self):
        data = Observation.objects.filter(satellite=self)
        return data.filter(vetted_status='verified').count()

    @property
    def empty_count(self):
        data = Observation.objects.filter(satellite=self)
        return data.filter(vetted_status='no_data').count()

    @property
    def unknown_count(self):
        data = Observation.objects.filter(satellite=self)
        return data.filter(vetted_status='unknown').count()

    @property
    def success_rate(self):
        try:
            return int(100 * (float(self.verified_count) / float(self.data_count)))
        except:
            return 0

    @property
    def empty_rate(self):
        try:
            return int(100 * (float(self.empty_count) / float(self.data_count)))
        except:
            return 0

    @property
    def unknown_rate(self):
        try:
            return int(100 * (float(self.unknown_count) / float(self.data_count)))
        except:
            return 0

    def __unicode__(self):
        return self.name


class Tle(models.Model):
    tle0 = models.CharField(max_length=100, blank=True)
    tle1 = models.CharField(max_length=200, blank=True)
    tle2 = models.CharField(max_length=200, blank=True)
    updated = models.DateTimeField(auto_now=True, blank=True)
    satellite = models.ForeignKey(Satellite, related_name='tles',
                                  on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        ordering = ['tle0']

    def __unicode__(self):
        return self.tle0


class Transmitter(models.Model):
    """Model for antennas transponders."""
    uuid = ShortUUIDField(db_index=True)
    description = models.TextField()
    alive = models.BooleanField(default=True)
    uplink_low = models.PositiveIntegerField(blank=True, null=True)
    uplink_high = models.PositiveIntegerField(blank=True, null=True)
    downlink_low = models.PositiveIntegerField(blank=True, null=True)
    downlink_high = models.PositiveIntegerField(blank=True, null=True)
    mode = models.ForeignKey(Mode, related_name='transmitters', blank=True,
                             null=True, on_delete=models.SET_NULL)
    invert = models.BooleanField(default=False)
    baud = models.FloatField(validators=[MinValueValidator(0)], null=True, blank=True)
    satellite = models.ForeignKey(Satellite, related_name='transmitters',
                                  on_delete=models.CASCADE, null=True, blank=True)

    def __unicode__(self):
        return self.description


class Observation(models.Model):
    """Model for SatNOGS observations."""
    satellite = models.ForeignKey(Satellite, related_name='observations',
                                  on_delete=models.SET_NULL, null=True, blank=True)
    transmitter = models.ForeignKey(Transmitter, related_name='observations',
                                    on_delete=models.SET_NULL, null=True, blank=True)
    tle = models.ForeignKey(Tle, related_name='observations',
                            on_delete=models.SET_NULL, null=True, blank=True)
    author = models.ForeignKey(User, related_name='observations',
                               on_delete=models.SET_NULL, null=True, blank=True)
    start = models.DateTimeField()
    end = models.DateTimeField()
    ground_station = models.ForeignKey(Station, related_name='observations',
                                       on_delete=models.SET_NULL, null=True, blank=True)
    payload = models.FileField(upload_to='data_payloads', blank=True, null=True)

network/users/forms.py
from django import forms

from network.users.models import User


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ("first_name", "last_name")

network/api/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.utils.timezone import now

from rest_framework import viewsets, mixins, status
from rest_framework.response import Response

from network.api.perms import StationOwnerCanEditPermission
from network.api import serializers, filters, pagination
from network.base.models import Observation, Station


class ObservationView(viewsets.ModelViewSet, mixins.UpdateModelMixin):
    queryset = Observation.objects.all()
    serializer_class = serializers.ObservationSerializer
    filter_class = filters.ObservationViewFilter
    permission_classes = [
        StationOwnerCanEditPermission
    ]
    pagination_class = pagination.LinkedHeaderPageNumberPagination

    def update(self, request, *args, **kwargs):
        if request.data.get('demoddata'):
            instance = self.get_object()
            instance.demoddata.create(payload_demod=request.data.get('demoddata'))

        super(ObservationView, self).update(request, *args, **kwargs)
        return Response(status=status.HTTP_200_OK)


class JobView(viewsets.ReadOnlyModelViewSet):
    queryset = Observation.objects.filter(payload='')
    serializer_class = serializers.JobSerializer
    filter_class = filters.ObservationViewFilter
    filter_fields = ('ground_station')

    def get_queryset(self):
        queryset = self.queryset.filter(start__gte=now())
        gs_id = self.request.query_params.get('ground_station', None)
        if gs_id and self.request.user.is_authenticated():
            gs = get_object_or_404(Station, id=gs_id)
            if gs.owner == self.request.user:
                gs.last_seen = now()
                gs.save()
        return queryset


class SettingsView(viewsets.ReadOnlyModelViewSet):
    queryset = Station.objects.all()
    lookup_field = 'uuid'

    def list(self, request):
        raise Http404()

    def retrieve(self, request, queryset=queryset, uuid=None):
        station = get_object_or_404(queryset, uuid=uuid)
        serializer = serializers.SettingsSerializer(station)
        return Response(serializer.data)

network/users/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.views.generic import RedirectView
from django.views.generic import UpdateView

from braces.views import LoginRequiredMixin

from rest_framework.authtoken.models import Token

from network.users.forms import UserForm
from network.users.models import User
from network.base.forms import StationForm
from network.base.models import Station, Observation, Antenna, Rig


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:view_user",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    form_class = UserForm

    model = User

    def get_success_url(self):
        return reverse("users:view_user",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


def view_user(request, username):
    """View for user page."""
    user = User.objects.get(username=username)
    observations = Observation.objects.filter(author=user)[0:10]
    stations = Station.objects.filter(owner=user)
    try:
        token = Token.objects.get(user=user)
    except:
        token = Token.objects.create(user=user)
    form = StationForm()
    antennas = Antenna.objects.all()
    rigs = Rig.objects.all()

    return render(request, 'users/user_detail.html',
                  {'user': user,
                   'observations': observations,
                   'stations': stations,
                   'token': token,
                   'form': form,
                   'antennas': antennas,
                   'rigs': rigs})

network/templates/base/about.html
{% extends "base.html" %}

{% block title %} - About{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
      <h1>About</h1>
      SatNOGS Network is a global management interface to facilitate multiple ground station
      operations remotely. An observer is able to take advantage of the full network of
      SatNOGS ground stations around the world.
      It's part of the <a href="https://satnogs.org/" target="_blank">SatNOGS project</a>.
      <h3>Observations</h3>
      The network is open to anyone. Any observer is able to utilize all available Ground Stations
      and communicate with Satellites. All observations results are public
      and all data are distributed freely under the
      <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank">Creative Commons Atribution-Share Alike</a> license.
      <h3>Ground Stations</h3>
      Whether you own satellite ground station equipment or you want
      to build one you can head to
      <a href="https://satnogs.org" target="_blank">SatNOGS Project site</a>
      to get up to date documentation and info on how to build a SatNOGS ground station (still under development).
      <h3>Coding</h3>
      Fluent in Python and/or JS? We need you to help with satnogs-network web application. Take a look to our
      <a href="https://gitlab.com/librespacefoundation/satnogs/satnogs-network/" target="_blank">source code</a> or visit
      our <a href="https://gitlab.com/librespacefoundation/satnogs/satnogs-network/issues" target="_blank">issues tracker</a>
      to start filling bugs, feature requests or code fixes for existing ones.
      Detailed contribution and development documentation is also availble at
      <a href="http://docs.satnogs.org" target="_blank">docs.satnogs.org</a>.
    </div>
  </div>
{% endblock content %}

network/templates/base/observation_new.html
{% extends "base.html" %}

{% load staticfiles %}
{% load tags %}

{% block title %} - New Observation{% endblock %}

{% block css %}
  <link href="{% static 'lib/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}

  <div class="row">
    <div class="col-md-12">
      <h2>New Observation</h2>
      <div class="timezone text-muted">
        <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
        Timeframes are in <a href="#" data-toggle="modal" data-target="#UTCModal">UTC</a>
      </div>
    </div>
  </div>

  <form class="form-horizontal" role="form" action="{% url 'base:observation_new' %}"
        method="post" data-obs-filter="{{ obs_filter.exists|lower }}" data-obs-filter-station="{{ obs_filter.ground_station }}"
        data-obs-filter-dates="{{ obs_filter.start_date }}" id="form-obs">{% csrf_token %}
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <label class="col-sm-3 control-label">Satellite</label>
          <div class="col-sm-9">
            {% if obs_filter.norad %}
              {% for satellite in satellites %}
                {% ifequal satellite.norad_cat_id obs_filter.norad %}
                  <input type="text" class="form-control" name="satellite-name"
                         readonly value="{{ satellite.norad_cat_id }} - {{ satellite.name }}">
                {% endifequal %}
              {% endfor %}
              <input type="hidden" name="satellite" value="{{ obs_filter.norad }}">
            {% else %}
              <select id="satellite-selection" class="form-control" name="satellite" autocomplete="off">
                <option value="" selected>Select a satellite</option>
                {% for satellite in satellites %}
                  <option data-norad="{{ satellite.norad_cat_id }}" value="{{ satellite.norad_cat_id }}">
                    {{ satellite.norad_cat_id }} - {{ satellite.name }}
                  </option>
                {% endfor %}
              </select>
            {% endif %}
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">Transmitter</label>
          <div class="col-sm-9">
            <select id="transmitter-selection" class="form-control" disabled name="transmitter" autocomplete="off">
              <option id="no-transmitter" value="" disabled selected>No transmitter available</option>
              {% for transmitter in transmitters %}
                <option data-satellite="{{ transmitter.satellite.norad_cat_id }}"
                        value="{{ transmitter.id }}" >
                  {{ transmitter.description }} - {{ transmitter.downlink_low|frq }} - {{ transmitter.mode|default:"" }}
                </option>
              {% endfor %}
            </select>
            {% for satellite in satellites %}
              <small class="tle" data-norad="{{ satellite.norad_cat_id }}">
                {% if satellite.tle_no %}
                  Using TLE {{ satellite.tle_no }} issued
                  {{ satellite.tle_epoch|timesince }} ago
                {% endif %}
              </small>
            {% endfor %}
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <label class="col-sm-3 control-label">Start Time</label>
          <div class="col-sm-9">
            <div class='input-group date' id="datetimepicker-start"
                 data-date-minstart="{{ date_min_start }}">
              {% if obs_filter.start_date %}
                <input type="text" class="form-control" name="start-time"
                       value="{{ obs_filter.start_date}}" readonly>
              {% else %}
                <input type="text"
                       class="form-control"
                       name="start-time"
                       data-date-format="YYYY-MM-DD HH:mm"
                       autocomplete="off">
              {% endif %}
              <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
              </span>
            </div>
          </div>
        </div>
        <div class="form-group">
          <label class="col-sm-3 control-label">End Time</label>
          <div class="col-sm-9">
            <div class='input-group date' id="datetimepicker-end"
                 data-date-maxrange="{{ date_max_range }}"
                 data-date-minend="{{ date_min_end }}">
              {% if obs_filter.end_date %}
                <input type="text" class="form-control" name="end-time"
                       value="{{ obs_filter.end_date}}" readonly>
              {% else %}
                <input type="text"
                       class="form-control"
                       name="end-time"
                       data-date-format="YYYY-MM-DD HH:mm"
                       autocomplete="off">
              {% endif %}
              <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>

    {% if obs_filter.ground_station %}
      <input type="hidden" name="ground_station" value="{{ obs_filter.ground_station }}">
    {% endif %}

    <div class="row">
      <div class="col-md-12">
        <button type="button" id="calculate-observation" class="btn btn-primary pull-right">
          Calculate
        </button>
      </div>
    </div>

    <div class="row calculation-result">
      <div class="col-md-12">
        <h3>Calculated Timeline</h3>
        <div id="loading" class="notice">Calculating</div>
        <div id="timeline"></div>
        <div id="hoverRes">
          <div class="coloredDiv"></div>
          <div id="name"></div>
          <div id="scrolled_date"></div>
        </div>
        <div id="windows-data"></div>
      </div>
    </div>

    <div class="row calculation-result">
      <div class="col-md-12">
        <button type="submit" id="schedule-observation" class="btn btn-success pull-right" disabled="True">
          Schedule
        </button>
      </div>
    </div>
  </form>

  <!-- UTC Modal -->
  {% include 'includes/utc.html' %}

{% endblock content %}

{% block javascript %}
  <script src="{% static 'lib/d3/d3.min.js' %}"></script>
  <script src="{% static 'lib/d3-timeline/src/d3-timeline.js' %}"></script>
  <script src="{% static 'lib/moment/min/moment.min.js' %}"></script>
  <script src="{% static 'lib/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js' %}"></script>
  <script src="{% static 'js/utc.js' %}"></script>
  <script src="{% static 'js/observation_new.js' %}"></script>
{% endblock javascript %}

network/templates/base/paginator.html
{% load url_replace %}
<nav>
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li>
        <a href="?{% url_replace request 'page' page_obj.previous_page_number %}">&laquo;</a>
      </li>
    {% else %}
      <li class="disabled">
        <a href="#"><span>&laquo;</span></a>
      </li>
    {% endif %}

    {% if show_first %}
      <li>
        <a href="?{% url_replace request 'page' 1 %}">1</a>
      </li>
      <li>
        <span>...</span>
      </li>
    {% endif %}

    {% for page in page_numbers %}
      {% ifequal page page_obj.number %}
        <li class="active">
          <a href="?{% url_replace request 'page' page %}">{{ page }}</a>
        </li>
      {% else %}
        <li>
          <a href="?{% url_replace request 'page' page %}">{{ page }}</a>
        </li>
      {% endifequal %}
    {% endfor %}

    {% if show_last %}
      <li>
        <span>...</span>
      </li>
      <li>
        <a href="?{% url_replace request 'page' 'last' %}">{{ paginator.num_pages }}</a>
      </li>
    {% endif %}

    {% if page_obj.has_next %}
      <li>
        <a href="?{% url_replace request 'page' page_obj.next_page_number %}">&raquo;</a>
      </li>
    {% else %}
      <li class="disabled">
        <a href="#"><span>&raquo;</span></a>
      </li>
    {% endif %}
  </ul>
</nav>

network/templates/base/settings_site.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %} - Site Settings{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
      <h1>Settings</h1>

      <h3>Fetch Data</h3>

      {% if fetch_data %}
        <p>Successfully fetch data from DB.</p>
        <p><a href="#" id="fetch_log">Show log</a></p>
        <code class="log">{{ fetch_data|linebreaks }}</code>
      {% else %}
        <p>You can update all Satellites and Transmitters data from DB.</p>

        <form id="fetchform" method="post" class="form-horizontal" role="form" action="{% url 'base:settings_site' %}">{% csrf_token %}
          <input type="hidden" name="fetch" value="true">
          <button class="btn btn-primary" type="submit">Fetch</button>
        </form>
      {% endif %}

    </div>
  </div>
{% endblock content %}

{% block javascript %}
  <script src="{% static 'js/settings_site.js' %}"></script>
{% endblock javascript %}

network/templates/base/stations.html
{% extends "base.html" %}
{% load tags %}
{% load staticfiles %}

{% block title %} - Ground Stations{% endblock %}

{% block content %}
  <h1>
    Ground Stations
    {% if user.is_authenticated %}
      <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#StationModal">New Ground Station</button>
    {% endif %}
  </h1>

  <div class="row">
    <div class="col-md-12">
      <table class="table table-hover">
        <thead>
          <th>ID</th>
          <th>Name</th>
          <th>Location</th>
          <th>Altitude</th>
          <th>Antennas</th>
          <th>Owner</th>
        </thead>
        <tbody>
          {% for station in stations.all %}
            <tr>
              <td>
                <a href="{% url 'base:station_view' id=station.id %}">
                  <span class="label
                               {% if station.online %}
                                 label-success
                               {% else %}
                                 label-danger
                               {% endif %}">
                    {{ station.id }}
                  </span>
                </a>
              </td>
              <td>
                <a href="{% url 'base:station_view' id=station.id %}">
                  {{ station.name }}
                </a>
              </td>
              {% if station.location %}
                <td title="{{ station.lat|floatformat:-3 }}°, {{ station.lng|floatformat:-3 }}°, {{ station.qthlocator }}">
                  {{ station.location }}
                </td>
              {% else %}
                <td>
                  {{ station.lat|floatformat:-3 }}°, {{ station.lng|floatformat:-3 }}°
                  {% if station.qthlocator %}
                    - {{ station.qthlocator }}
                  {% endif %}
                </td>
              {% endif %}
              <td>{{ station.alt}} m</td>
              <td>
                {% for antenna in station.antenna.all %}
                  {{ antenna.band}} {{ antenna.get_antenna_type_display }} | {{ antenna.frequency|frq }} - {{ antenna.frequency_max|frq }}<br>
                {% endfor %}
              </td>
              <td>
                <a href="{% url 'users:view_user' username=station.owner.username %}">
                  {{ station.owner.displayname }}
                </a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <!-- Station Modal -->
  {% include 'includes/station_edit.html' %}
{% endblock content %}

{% block javascript %}
  <script src="{% static 'js/gridsquare.js' %}"></script>
{% endblock javascript %}